FROM node:20-bookworm

WORKDIR /app

# 🆕 Устанавливаем OpenSSL 3 (стандарт для Debian Bookworm)
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3001

CMD ["npm", "start"]